### ISSUE TITLE
nil pointer crash on missing BSL

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#1071]
During repeatability testing, I encountered the error below:

```bash
2023-09-21T22:29:06.455Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:154  Kube objects recover    {"VolumeReplicationGroup": "jenkins/bb", "rid": "9f4ed57a-498b-48a2-9f91-68bf5208d6b3", "State": "primary", "s3 url": "http://s3-openshift-storage.apps.cluster5.local/", "s3 bucket": "odrbucket-aba4234875cd", "s3 region": "noobaa", "s3 key prefix": "jenkins/bb/kube-objects/1/", "secret key ref": "&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:cloud-credentials-cluster5,},Key:aws,Optional:nil,}", "CA certificates": "", "source namespace": "jenkins", "target namespace": "jenkins", "request namespace": "openshift-adp", "capture name": "jenkins--bb--1----s3profile-cluster5-ocs-external-storagecluster", "recover name": "jenkins--bb--0", "label set": {"ramendr.openshift.io/owner-name":"bb","ramendr.openshift.io/owner-namespace-name":"jenkins"}, "annotations": {}}
2023-09-21T22:29:06.455Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:676  Backup  {"VolumeReplicationGroup": "jenkins/bb", "rid": "9f4ed57a-498b-48a2-9f91-68bf5208d6b3", "State": "primary", "phase": "FailedValidation", "warnings": 0, "errors": 0, "failure": "", "validation errors": ["an existing backup storage location wasn't specified at backup creation time and the default 'jenkins--bb--1----s3profile-cluster5-ocs-external-storagecluster' wasn't found. Please address this issue (see `velero ba
ckup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io \"jenkins--bb--1----s3profile-cluster5-ocs-external-storagecluster\" not found"]}
2023-09-21T22:29:06.455Z        ERROR   controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:661      Kube objects group recover error        {"VolumeReplicationGroup": "jenkins/bb", "rid": "9f4ed57a-498b-48a2-9f91-68bf5208d6b3", "State": "primary", "number": 1, "profile": "s3profile-cluster5-ocs-external-storagecluster", "group": 0, "name": "", "error": "backupFailedValidation"}
github.com/ramendr/ramen/controllers.(*VRGInstance).kubeObjectsRecoveryStartOrResume
        /workspace/controllers/vrg_kubeobjects.go:661
github.com/ramendr/ramen/controllers.(*VRGInstance).kubeObjectsRecover
        /workspace/controllers/vrg_kubeobjects.go:542
github.com/ramendr/ramen/controllers.(*VRGInstance).restorePVsAndPVCsFromS3
        /workspace/controllers/vrg_volrep.go:1805
github.com/ramendr/ramen/controllers.(*VRGInstance).clusterDataRestoreForVolRep
        /workspace/controllers/vrg_volrep.go:1744
github.com/ramendr/ramen/controllers.(*VRGInstance).clusterDataRestore
        /workspace/controllers/volumereplicationgroup_controller.go:700
github.com/ramendr/ramen/controllers.(*VRGInstance).processAsPrimary
        /workspace/controllers/volumereplicationgroup_controller.go:944
github.com/ramendr/ramen/controllers.(*VRGInstance).processVRGActions
        /workspace/controllers/volumereplicationgroup_controller.go:621
github.com/ramendr/ramen/controllers.(*VRGInstance).processVRG
        /workspace/controllers/volumereplicationgroup_controller.go:594
github.com/ramendr/ramen/controllers.(*VolumeReplicationGroupReconciler).Reconcile
        /workspace/controllers/volumereplicationgroup_controller.go:483
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
2023-09-21T22:29:06.455Z        INFO    controllers.VolumeReplicationGroup.vrginstance  runtime/panic.go:884    Exiting processing VolumeReplicationGroup       {"VolumeReplicationGroup": "jenkins/bb", "rid": "9f4ed57a-498b-48a2-9f91-68bf5208d6b3", "State": "primary"}
2023-09-21T22:29:06.455Z        INFO    controllers.VolumeReplicationGroup      runtime/panic.go:884    Exiting reconcile loop  {"VolumeReplicationGroup": "jenkins/bb", "rid": "9f4ed57a-498b-48a2-9f91-68bf5208d6b3"}
2023-09-21T22:29:06.455Z        INFO    controller/controller.go:118    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "volumereplicationgroup", "controllerGroup": "ramendr.openshift.io", "controllerKind": "VolumeReplicationGroup", "VolumeReplicationGroup": {"name":"bb","namespace":"jenkins"}, "namespace": "jenkins", "name": "bb", "reconcileID": "3f478028-035a-45ed-a854-246bad8be07c"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2015295]

goroutine 852 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x2309fe0, 0x4095e00})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/ramendr/ramen/controllers.(*VRGInstance).getRecoverOrProtectRequest.func4({0x0, 0x0})
        /workspace/controllers/vrg_kubeobjects.go:611 +0x95
github.com/ramendr/ramen/controllers.(*VRGInstance).kubeObjectsRecoveryStartOrResume(0xc00168a140, 0xc001939540, {{0x2c07478, 0xc0035dae00}, {{0xc0018ae990, 0x2e}, {0xc000ee9308, 0x16}, {0xc0018ae960, 0x2f}, ...}}, ...)
        /workspace/controllers/vrg_kubeobjects.go:662 +0xa4f
github.com/ramendr/ramen/controllers.(*VRGInstance).kubeObjectsRecover(0xc00168a140, 0x0?, {{0xc0018ae990, 0x2e}, {0xc000ee9308, 0x16}, {0xc0018ae960, 0x2f}, {0xc0018da09a, 0x6}, ...}, ...)
        /workspace/controllers/vrg_kubeobjects.go:542 +0x6bd
github.com/ramendr/ramen/controllers.(*VRGInstance).restorePVsAndPVCsFromS3(0xc00168a140, 0xc001939540)
        /workspace/controllers/vrg_volrep.go:1805 +0x678
github.com/ramendr/ramen/controllers.(*VRGInstance).clusterDataRestoreForVolRep(0xc00168a140, 0xc00118f540)
        /workspace/controllers/vrg_volrep.go:1744 +0x11d
github.com/ramendr/ramen/controllers.(*VRGInstance).clusterDataRestore(0xc00168a140, 0xc00118f540)
        /workspace/controllers/volumereplicationgroup_controller.go:700 +0x5cc
github.com/ramendr/ramen/controllers.(*VRGInstance).processAsPrimary(0xc00168a140)
        /workspace/controllers/volumereplicationgroup_controller.go:944 +0x11d
github.com/ramendr/ramen/controllers.(*VRGInstance).processVRGActions(0xc00168a140)
        /workspace/controllers/volumereplicationgroup_controller.go:621 +0x265
github.com/ramendr/ramen/controllers.(*VRGInstance).processVRG(0xc00168a140)
        /workspace/controllers/volumereplicationgroup_controller.go:594 +0x6c5
github.com/ramendr/ramen/controllers.(*VolumeReplicationGroupReconciler).Reconcile(0xc0005ad730, {0x2c06bf0?, 0xc0017f26f0}, {{{0xc0018cd308, 0x7}, {0xc0018cd306, 0x2}}})
        /workspace/controllers/volumereplicationgroup_controller.go:483 +0xb5a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2c06bf0?, {0x2c06bf0?, 0xc0017f26f0?}, {{{0xc0018cd308?, 0x21e4aa0?}, {0xc0018cd306?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000517680, {0x2c06b48, 0xc000f391c0}, {0x23c7c00?, 0xc00102c020?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000517680, {0x2c06b48, 0xc000f391c0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
```

The Jenkins installation under test uses a single restore group, while MariaDB uses 4 restore groups. This issue seemed to crash the pods and restart them, though eventually they recovered without any intervention from me:

```bash
oc get pods -n openshift-dr-system
NAME                                            READY   STATUS    RESTARTS       AGE
pod/ramen-dr-cluster-operator-cddbb899c-tljx9   2/2     Running   16 (23m ago)   27h
```

I've attached one of these logs to the issue, where I encountered this with MariaDB.

[ramen_log_nil_pointer_error.log](https://github.com/RamenDR/ramen/files/12706948/ramen_log_nil_pointer_error.log)

**Comment by hatfieldbrian** [comment]
Labeled medium priority because it occurred multiple times when testing failover and relocate repeatability with modern applications.  System did recover after 16 restarts.
