### ISSUE TITLE
drenv: curl: (28) Failed to connect to nginx.ns2.svc.clusterset.local port 80 after 132054 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1286]
Random error in submariner test:

```
2024-03-25 15:31:59,642 DEBUG   [hub/1] Looking up 'nginx.ns2.svc.clusterset.local' in cluster 'dr1'
2024-03-25 15:32:04,990 DEBUG   [hub/1] Lookup completed in 5.347 seconds
2024-03-25 15:32:04,990 DEBUG   [hub/1] ;; communications error to 10.96.0.10#53: timed out
2024-03-25 15:32:04,990 DEBUG   [hub/1] Server:		10.96.0.10
2024-03-25 15:32:04,990 DEBUG   [hub/1] Address:	10.96.0.10#53
2024-03-25 15:32:04,990 DEBUG   [hub/1] 
2024-03-25 15:32:04,991 DEBUG   [hub/1] Name:	nginx.ns2.svc.clusterset.local
2024-03-25 15:32:04,991 DEBUG   [hub/1] Address: 242.1.255.254
2024-03-25 15:32:04,991 DEBUG   [hub/1] 
2024-03-25 15:32:04,991 DEBUG   [hub/1] 
2024-03-25 15:32:04,991 DEBUG   [hub/1] Accessing 'nginx.ns2.svc.clusterset.local' in cluster 'dr1'
...
drenv.commands.Error: Command failed:
   command: ('addons/submariner/test', 'hub', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/ramen/test/addons/submariner/test", line 259, in <module>
          test_connectivity(clusters[0], NS2)
        File "/home/nsoffer/ramen/test/addons/submariner/test", line 213, in test_connectivity
          out = kubectl.exec(
                ^^^^^^^^^^^^^
        File "/home/nsoffer/ramen/test/drenv/kubectl.py", line 52, in exec
          return _run("exec", *args, context=context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/nsoffer/ramen/test/drenv/kubectl.py", line 137, in _run
          return commands.run(*cmd)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/nsoffer/ramen/test/drenv/commands.py", line 91, in run
          raise Error(args, error, exitcode=p.returncode, output=output.decode())
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'exec', '--context', 'dr1', 'test', '--namespace=ns2', '--', 'curl', '--no-progress-meter', 'nginx.ns2.svc.clusterset.local')
         exitcode: 28
         error:
            curl: (28) Failed to connect to nginx.ns2.svc.clusterset.local port 80 after 132054 ms: Couldn't connect to server
            command terminated with exit code 28
```

## System state after the error

Tested 4 hours after the failure.

subctl show all check:

```
$ subctl show all --context dr1
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY   CLUSTER   REMOTE IP        NAT   CABLE DRIVER   SUBNETS        STATUS      RTT avg.     
dr2       dr2       192.168.22.224   no    vxlan          242.1.0.0/16   connected   1.286563ms   

 ✓ Showing Endpoints
CLUSTER   ENDPOINT IP      PUBLIC IP        CABLE DRIVER   TYPE     
dr1       192.168.22.6     125.16.100.118   vxlan          local    
dr2       192.168.22.224   125.16.100.118   vxlan          remote   

 ✓ Showing Gateways
NODE   HA STATUS   SUMMARY                               
dr1    active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]
        Global CIDR:     242.0.0.0/16

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-routeagent           quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-globalnet            quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.3       release-0.16-03f30315107e   amd64   
submariner-operator             quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
```

submariner-operator namespace on cluster dr1

```
$ kubectl get all -n submariner-operator --context dr1
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/submariner-gateway-6w6zk                         1/1     Running   0          4h8m
pod/submariner-globalnet-6bg4b                       1/1     Running   0          4h8m
pod/submariner-lighthouse-agent-58949575c6-n9lzt     1/1     Running   0          4h8m
pod/submariner-lighthouse-coredns-76d97449b5-7nd6m   1/1     Running   0          4h8m
pod/submariner-lighthouse-coredns-76d97449b5-nzxq4   1/1     Running   0          4h8m
pod/submariner-metrics-proxy-4nr2t                   2/2     Running   0          4h8m
pod/submariner-operator-7865db7657-27g4p             1/1     Running   0          13h
pod/submariner-routeagent-4rgwr                      1/1     Running   0          4h8m

NAME                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/submariner-gateway-metrics              ClusterIP   10.103.30.232    <none>        8080/TCP   4h8m
service/submariner-globalnet-metrics            ClusterIP   10.105.88.40     <none>        8081/TCP   4h8m
service/submariner-lighthouse-agent-metrics     ClusterIP   10.104.227.246   <none>        8082/TCP   4h8m
service/submariner-lighthouse-coredns           ClusterIP   10.111.97.106    <none>        53/UDP     4h8m
service/submariner-lighthouse-coredns-metrics   ClusterIP   10.111.48.3      <none>        9153/TCP   4h8m
service/submariner-operator-metrics             ClusterIP   10.107.167.4     <none>        8383/TCP   13h

NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                AGE
daemonset.apps/submariner-gateway         1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-globalnet       1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-metrics-proxy   1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-routeagent      1         1         1       1            1           <none>                       4h8m

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/submariner-lighthouse-agent     1/1     1            1           4h8m
deployment.apps/submariner-lighthouse-coredns   2/2     2            2           4h8m
deployment.apps/submariner-operator             1/1     1            1           13h

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/submariner-lighthouse-agent-58949575c6     1         1         1       4h8m
replicaset.apps/submariner-lighthouse-coredns-76d97449b5   2         2         2       4h8m
replicaset.apps/submariner-operator-7865db7657             1         1         1       13h
```

submariner-operator namespace on cluster dr2

```
$ kubectl get all -n submariner-operator --context dr2
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/submariner-gateway-lmzgt                         1/1     Running   0          4h8m
pod/submariner-globalnet-mhxtv                       1/1     Running   0          4h8m
pod/submariner-lighthouse-agent-5b5b678cf8-jvrx8     1/1     Running   0          4h8m
pod/submariner-lighthouse-coredns-75bfb8ffc4-pg258   1/1     Running   0          4h8m
pod/submariner-lighthouse-coredns-75bfb8ffc4-vg2hq   1/1     Running   0          4h8m
pod/submariner-metrics-proxy-wrbpj                   2/2     Running   0          4h8m
pod/submariner-operator-7865db7657-84rwj             1/1     Running   0          13h
pod/submariner-routeagent-sv5kr                      1/1     Running   0          4h8m

NAME                                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/submariner-gateway-metrics              ClusterIP   10.103.128.173   <none>        8080/TCP   4h8m
service/submariner-globalnet-metrics            ClusterIP   10.100.149.196   <none>        8081/TCP   4h8m
service/submariner-lighthouse-agent-metrics     ClusterIP   10.107.163.172   <none>        8082/TCP   4h8m
service/submariner-lighthouse-coredns           ClusterIP   10.101.58.75     <none>        53/UDP     4h8m
service/submariner-lighthouse-coredns-metrics   ClusterIP   10.97.244.67     <none>        9153/TCP   4h8m
service/submariner-operator-metrics             ClusterIP   10.104.25.81     <none>        8383/TCP   13h

NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                AGE
daemonset.apps/submariner-gateway         1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-globalnet       1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-metrics-proxy   1         1         1       1            1           submariner.io/gateway=true   4h8m
daemonset.apps/submariner-routeagent      1         1         1       1            1           <none>                       4h8m

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/submariner-lighthouse-agent     1/1     1            1           4h8m
deployment.apps/submariner-lighthouse-coredns   2/2     2            2           4h8m
deployment.apps/submariner-operator             1/1     1            1           13h

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/submariner-lighthouse-agent-5b5b678cf8     1         1         1       4h8m
replicaset.apps/submariner-lighthouse-coredns-75bfb8ffc4   2         2         2       4h8m
replicaset.apps/submariner-operator-7865db7657             1         1         1       13h
```

State on cluster `dr2`, exporting a the `nginx` service in namespace `ns2`

```
$ kubectl get all -n ns2 --context dr2
NAME                         READY   STATUS    RESTARTS   AGE
pod/nginx-656fb4d658-s5snz   1/1     Running   0          12h

NAME                                                  TYPE        CLUSTER-IP       EXTERNAL-IP     PORT(S)   AGE
service/nginx                                         ClusterIP   10.111.113.101   <none>          80/TCP    12h
service/submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast   ClusterIP   10.102.120.119   242.1.255.253   80/TCP    3h53m

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx   1/1     1            1           12h

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-656fb4d658   1         1         1       12h
```

submariner service:

```
$ kubectl get service/submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast -n ns2 --context dr2 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-25T13:31:19Z"
  finalizers:
  - submariner.io/globalnet-internal-service
  labels:
    submariner.io/exportedServiceRef: nginx
  name: submariner-lpq6zr4tl4o5qvrv2t7o3l3gawkagast
  namespace: ns2
  resourceVersion: "139378"
  uid: e413e726-2529-4f15-9c6e-6872512a7015
spec:
  clusterIP: 10.102.120.119
  clusterIPs:
  - 10.102.120.119
  externalIPs:
  - 242.1.255.253
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

ngnix service on cluster dr2

```
$ kubectl describe service nginx -n ns2 --context dr2
Name:              nginx
Namespace:         ns2
Labels:            <none>
Annotations:       <none>
Selector:          app=nginx
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.111.113.101
IPs:               10.111.113.101
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.244.0.29:80
Session Affinity:  None
Events:            <none>
```

Trying to access nginx on cluster dr2:

```
$ kubectl exec --context dr2 test --namespace=ns1 -it -- curl http://10.111.113.101 | grep h1
<h1>Welcome to nginx!</h1>

$ kubectl exec --context dr2 test --namespace=ns1 -it -- curl http://10.244.0.29 | grep h1
<h1>Welcome to nginx!</h1>
```

Trying nslookup in cluster `dr1`:

```
$ kubectl exec test -n ns2 --context dr1 -- nslookup nginx.ns2.svc.clusterset.local
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	nginx.ns2.svc.clusterset.local
Address: 242.1.255.254
```

Trying to access the service with curl:

```
$ kubectl exec --context dr1 test --namespace=ns2 -- curl --no-progress-meter nginx.ns2.svc.clusterset.local
curl: (28) Failed to connect to nginx.ns2.svc.clusterset.local port 80 after 130160 ms: Couldn't connect to server
command terminated with exit code 28
```

## Logs

[000.log](https://github.com/RamenDR/ramen/files/14747289/000.log)

## Workaround

Redeploying submariner fixed the issue:

```
$ addons/submariner/start hub dr1 dr2
Waiting until broker 'hub' is ready
Cluster 'hub' is ready
Creating submariner configuration directory '/home/nsoffer/.config/drenv/hub/submariner'
Deploying submariner broker in cluster 'hub'
Broker info stored in '/home/nsoffer/.config/drenv/hub/submariner/broker-info.subm'
Waiting for submariner broker deployments in cluster 'hub'
Waiting until deployment 'submariner-operator' exists in cluster 'hub'
'deploy/submariner-operator' output='jsonpath={.metadata.name}' found in 0.09 seconds
Waiting until deployment 'submariner-operator' is rolled out in cluster 'hub'
deployment "submariner-operator" successfully rolled out
Waiting until cluster 'dr1' is ready
Cluster 'dr1' is ready
Joining cluster 'dr1' to broker
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]
   There are 1 node(s) labeled as gateways:
    - dr1
Waiting until cluster 'dr2' is ready
Cluster 'dr2' is ready
Joining cluster 'dr2' to broker
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]
   There are 1 node(s) labeled as gateways:
    - dr2
Waiting for submariner deployuments in cluster 'dr1'
Waiting until deployment 'submariner-operator' exists in cluster 'dr1'
'deploy/submariner-operator' output='jsonpath={.metadata.name}' found in 0.09 seconds
Waiting until deployment 'submariner-operator' is rolled out in cluster 'dr1'
deployment "submariner-operator" successfully rolled out
Waiting until deployment 'submariner-lighthouse-agent' exists in cluster 'dr1'
'deploy/submariner-lighthouse-agent' output='jsonpath={.metadata.name}' found in 0.06 seconds
Waiting until deployment 'submariner-lighthouse-agent' is rolled out in cluster 'dr1'
deployment "submariner-lighthouse-agent" successfully rolled out
Waiting until deployment 'submariner-lighthouse-coredns' exists in cluster 'dr1'
'deploy/submariner-lighthouse-coredns' output='jsonpath={.metadata.name}' found in 0.08 seconds
Waiting until deployment 'submariner-lighthouse-coredns' is rolled out in cluster 'dr1'
deployment "submariner-lighthouse-coredns" successfully rolled out
Waiting for submariner deployuments in cluster 'dr2'
Waiting until deployment 'submariner-operator' exists in cluster 'dr2'
'deploy/submariner-operator' output='jsonpath={.metadata.name}' found in 0.09 seconds
Waiting until deployment 'submariner-operator' is rolled out in cluster 'dr2'
deployment "submariner-operator" successfully rolled out
Waiting until deployment 'submariner-lighthouse-agent' exists in cluster 'dr2'
'deploy/submariner-lighthouse-agent' output='jsonpath={.metadata.name}' found in 0.08 seconds
Waiting until deployment 'submariner-lighthouse-agent' is rolled out in cluster 'dr2'
Waiting for deployment "submariner-lighthouse-agent" rollout to finish: 0 of 1 updated replicas are available...
deployment "submariner-lighthouse-agent" successfully rolled out
Waiting until deployment 'submariner-lighthouse-coredns' exists in cluster 'dr2'
'deploy/submariner-lighthouse-coredns' output='jsonpath={.metadata.name}' found in 0.09 seconds
Waiting until deployment 'submariner-lighthouse-coredns' is rolled out in cluster 'dr2'
deployment "submariner-lighthouse-coredns" successfully rolled out
```

Running the test again:

```
$ addons/submariner/test hub dr1 dr2
Checking submariner status in cluster 'hub'
Check completed in 0.402 seconds
NAMESPACE               NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   service-discovery, connectivity   yes         242.0.0.0/8      65536                                      

COMPONENT             REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-operator   quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   


Checking submariner status in cluster 'dr1'
Check completed in 2.012 seconds

GATEWAY   CLUSTER   REMOTE IP        NAT   CABLE DRIVER   SUBNETS        STATUS      RTT avg.     
dr2       dr2       192.168.22.224   no    vxlan          242.1.0.0/16   connected   1.059176ms   

CLUSTER   ENDPOINT IP      PUBLIC IP        CABLE DRIVER   TYPE     
dr1       192.168.22.6     125.16.100.118   vxlan          local    
dr2       192.168.22.224   125.16.100.118   vxlan          remote   

NODE   HA STATUS   SUMMARY                               
dr1    active      All connections (1) are established   

    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]
        Global CIDR:     242.0.0.0/16

COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-routeagent           quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-globalnet            quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.3       release-0.16-03f30315107e   amd64   
submariner-operator             quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   


Checking submariner status in cluster 'dr2'
Check completed in 2.046 seconds

GATEWAY   CLUSTER   REMOTE IP      NAT   CABLE DRIVER   SUBNETS        STATUS      RTT avg.       
dr1       dr1       192.168.22.6   no    vxlan          242.0.0.0/16   connected   250.328794ms   

CLUSTER   ENDPOINT IP      PUBLIC IP        CABLE DRIVER   TYPE     
dr2       192.168.22.224   125.16.100.118   vxlan          local    
dr1       192.168.22.6     125.16.100.118   vxlan          remote   

NODE   HA STATUS   SUMMARY                               
dr2    active      All connections (1) are established   

    Discovered network details via Submariner:
        Network plugin:  generic
        Service CIDRs:   [10.96.0.0/12]
        Cluster CIDRs:   [10.244.0.0/16]
        Global CIDR:     242.1.0.0/16

COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-routeagent           quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-globalnet            quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.3       release-0.16-03f30315107e   amd64   
submariner-operator             quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   


Deploying namespace 'ns1' on clusters 'dr1'
namespace/ns1 unchanged
service/nginx unchanged
deployment.apps/nginx unchanged
Deploying namespace 'ns1' on clusters 'dr2'
namespace/ns1 unchanged
pod/test unchanged
Deploying namespace 'ns2' on clusters 'dr2'
namespace/ns2 unchanged
service/nginx unchanged
deployment.apps/nginx unchanged
Deploying namespace 'ns2' on clusters 'dr1'
namespace/ns2 unchanged
pod/test unchanged
Waiting until 'nginx' is rolled out in cluster 'dr1'
deployment.apps/nginx condition met
Waiting until test pod is ready in cluster 'dr2'
pod/test condition met
Waiting until 'nginx' is rolled out in cluster 'dr2'
deployment.apps/nginx condition met
Waiting until test pod is ready in cluster 'dr1'
pod/test condition met
Export service in namespace 'ns1' in cluster 'dr1'
Export service in namespace 'ns2' in cluster 'dr2'
Waiting for service in namespace 'ns1' in cluster 'dr1'
serviceexport.multicluster.x-k8s.io/nginx condition met
Name:         nginx
Namespace:    ns1
Labels:       <none>
Annotations:  <none>
API Version:  multicluster.x-k8s.io/v1alpha1
Kind:         ServiceExport
Metadata:
  Creation Timestamp:  2024-03-25T04:31:57Z
  Generation:          1
  Resource Version:    180408
  UID:                 f84740b5-0622-4151-b343-f5a4e6335622
Status:
  Conditions:
    Last Transition Time:  2024-03-25T18:24:39Z
    Message:               
    Reason:                
    Status:                True
    Type:                  Valid
    Last Transition Time:  2024-03-25T04:31:59Z
    Message:               Service was successfully exported to the broker
    Reason:                
    Status:                True
    Type:                  Ready
Events:                    <none>

Waiting for service in namespace 'ns1' in cluster 'dr2'
'serviceimports/nginx' output='jsonpath={.status.clusters}' found in 0.07 seconds
Name:         nginx
Namespace:    ns1
Labels:       <none>
Annotations:  <none>
API Version:  multicluster.x-k8s.io/v1alpha1
Kind:         ServiceImport
Metadata:
  Creation Timestamp:  2024-03-25T18:24:56Z
  Generation:          1
  Resource Version:    214204
  UID:                 277de2ba-76a5-4047-b7d9-758386d4feaa
Spec:
  Ports:
    Port:      80
    Protocol:  TCP
  Type:        ClusterSetIP
Status:
  Clusters:
    Cluster:  dr1
Events:       <none>

Waiting for service in namespace 'ns2' in cluster 'dr2'
serviceexport.multicluster.x-k8s.io/nginx condition met
Name:         nginx
Namespace:    ns2
Labels:       <none>
Annotations:  <none>
API Version:  multicluster.x-k8s.io/v1alpha1
Kind:         ServiceExport
Metadata:
  Creation Timestamp:  2024-03-25T04:31:57Z
  Generation:          1
  Resource Version:    214198
  UID:                 502322aa-8d5b-490c-bb07-f4bbc004763d
Status:
  Conditions:
    Last Transition Time:  2024-03-25T18:24:55Z
    Message:               
    Reason:                
    Status:                True
    Type:                  Valid
    Last Transition Time:  2024-03-25T04:31:58Z
    Message:               Service was successfully exported to the broker
    Reason:                
    Status:                True
    Type:                  Ready
Events:                    <none>

Waiting for service in namespace 'ns2' in cluster 'dr1'
'serviceimports/nginx' output='jsonpath={.status.clusters}' found in 0.10 seconds
Name:         nginx
Namespace:    ns2
Labels:       <none>
Annotations:  <none>
API Version:  multicluster.x-k8s.io/v1alpha1
Kind:         ServiceImport
Metadata:
  Creation Timestamp:  2024-03-25T18:24:57Z
  Generation:          2
  Resource Version:    180519
  UID:                 8adcb222-29fc-4e46-88da-1481d081ede9
Spec:
  Ports:
    Port:      80
    Protocol:  TCP
  Type:        ClusterSetIP
Status:
  Clusters:
    Cluster:  dr2
Events:       <none>

Looking up 'nginx.ns1.svc.clusterset.local' in cluster 'dr2'
Lookup completed in 5.205 seconds
;; communications error to 10.96.0.10#53: timed out
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	nginx.ns1.svc.clusterset.local
Address: 242.0.255.253


Accessing 'nginx.ns1.svc.clusterset.local' in cluster 'dr2'
Looking up 'nginx.ns2.svc.clusterset.local' in cluster 'dr1'
Lookup completed in 0.202 seconds
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	nginx.ns2.svc.clusterset.local
Address: 242.1.255.253


Accessing 'nginx.ns2.svc.clusterset.local' in cluster 'dr1'
Unexport service in namespace 'ns1' in cluster 'dr1'
Unexport service in namespace 'ns2' in cluster 'dr2'
Undeploying namespace 'ns1' in cluster 'dr1'
namespace "ns1" deleted
service "nginx" deleted
deployment.apps "nginx" deleted
Undeploying namespace 'ns1' in cluster 'dr2'
namespace "ns1" deleted
pod "test" deleted
Undeploying namespace 'ns2' in cluster 'dr2'
namespace "ns2" deleted
service "nginx" deleted
deployment.apps "nginx" deleted
Undeploying namespace 'ns2' in cluster 'dr1'
namespace "ns2" deleted
pod "test" deleted
Waiting for deletion of namespace 'ns1' in cluster 'dr1'
namespace "ns1" deleted
Waiting for deletion of namespace 'ns1' in cluster 'dr2'
namespace "ns1" deleted
Waiting for deletion of namespace 'ns2' in cluster 'dr2'
Waiting for deletion of namespace 'ns2' in cluster 'dr1'

```

## Stats
- count: 1

## Links

- [thread in sumbariner slack](https://kubernetes.slack.com/archives/C010RJV694M/p1711390178546519)

## Tasks

- [x] Try with submariner 0.17.0 (see #1274)

**Comment by nirs** [comment]
Could not reproduce with 0.17.0 so far. We can reopen if this will be reproduced.
