### ISSUE TITLE
drenv dump is broken

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#797]
Since we added support for --skip-tests, `drenv dump` is broken:

```
$ drenv dump /home/nsoffer/drenv/barak-regional-dr.yaml 
Traceback (most recent call last):
  File "/home/nsoffer/.venv/ramen/bin/drenv", line 33, in <module>
    sys.exit(load_entry_point('drenv', 'console_scripts', 'drenv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsoffer/src/ramen/test/drenv/__main__.py", line 46, in main
    func(env, args)
TypeError: cmd_dump() takes 1 positional argument but 2 were given
```

Easy to fix, but it shows that we don't have a test for this!

**Comment by nirs** [comment]
Fixed by #800, but the PR was missing a Fixes: header and was not linked to this issue.
