### ISSUE TITLE
drenv stop is potentially not idempotent, i.e a reinvocation fails if one of the clusters are already stopped

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#817]
What I did:
- invoked drenv stop for the regional-dr.yaml
    - That timed out for one of the clusters
- Invoked it again
    - Failed for one (first) of the clusters stating it is unable to talk to the API server, because that instance was already stopped

Not a priority issue, but noting the expectation mismatch and the output from the commands below:
```
(ramen) [e2e@localhost test]$ drenv stop ./regional-dr.yaml 
2023-03-30 20:58:46,931 INFO    [rdr] Stopping environment
2023-03-30 20:58:47,061 INFO    [dr1] Stopping cluster
2023-03-30 20:58:47,081 INFO    [dr2] Stopping cluster
2023-03-30 20:58:47,113 INFO    [hub] Stopping cluster
2023-03-30 20:58:57,030 INFO    [hub] Cluster stopped in 9.92 seconds
2023-03-30 21:00:23,794 INFO    [dr2] Cluster stopped in 96.71 seconds
2023-03-30 21:00:51,423 ERROR   [dr1] Cluster failed
Traceback (most recent call last):
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/__main__.py", line 111, in execute
    f.result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/__main__.py", line 147, in stop_cluster
    stop_minikube_cluster(profile)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/__main__.py", line 199, in stop_minikube_cluster
    minikube.stop(profile["name"])
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/minikube.py", line 57, in stop
    _watch("stop", profile=profile)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/minikube.py", line 77, in _watch
    for line in commands.watch(*cmd):
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/commands.py", line 127, in watch
    raise Error(args, p.returncode, error)
drenv.commands.Error: Command failed:
   command: ('minikube', 'stop', '--profile', 'dr1')
   exitcode: 82
   error:
      X Exiting due to GUEST_STOP_TIMEOUT: Temporary Error: stop: unable to stop vm, current state "Running"
      * 
      ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
      │                                                                                             │
      │    * If the above advice does not help, please let us know:                                 │
      │      https://github.com/kubernetes/minikube/issues/new/choose                               │
      │                                                                                             │
      │    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
      │    * Please also attach the following file to the GitHub issue:                             │
      │    * - /tmp/minikube_stop_0d232b9ceef8f49971ab30f014df3b12701fcc91_0.log                    │
      │                                                                                             │
      ╰─────────────────────────────────────────────────────────────────────────────────────────────╯
```

Instance 2: post the above instance failed as noted
```
(ramen) [e2e@localhost test]$ drenv stop ./regional-dr.yaml 
2023-03-30 21:03:11,932 INFO    [rdr] Stopping environment
2023-03-30 21:03:15,148 ERROR   [dr1] Cluster failed
Traceback (most recent call last):
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/__main__.py", line 111, in execute
    f.result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/__main__.py", line 133, in stop_cluster
    cluster_status = cluster.status(profile["name"])
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/cluster.py", line 23, in status
    out = kubectl.version(context=name, output="json")
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/kubectl.py", line 13, in version
    return _run("version", *args, context=context)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/kubectl.py", line 87, in _run
    return commands.run(*cmd)
  File "/home/e2e/go/src/github.com/ramendr/ramen/test/drenv/commands.py", line 73, in run
    raise Error(args, cp.returncode, error, output=output)
drenv.commands.Error: Command failed:
   command: ('kubectl', 'version', '--context', 'dr1', '--output', 'json')
   exitcode: 1
   output:
      {
        "clientVersion": {
          "major": "1",
          "minor": "23",
          "gitVersion": "v1.23.4",
          "gitCommit": "e6c093d87ea4cbb530a7b2ae91e54c0842d8308a",
          "gitTreeState": "clean",
          "buildDate": "2022-02-16T12:38:05Z",
          "goVersion": "go1.17.7",
          "compiler": "gc",
          "platform": "linux/amd64"
        }
      }
   error:
      Unable to connect to the server: dial tcp 192.168.122.105:8443: connect: no route to host

(ramen) [e2e@localhost test]$ minikube profile list
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
| Profile | VM Driver |  Runtime   |       IP        | Port | Version | Status  | Nodes | Active |
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
| dr1     | kvm2      | containerd | 192.168.122.105 | 8443 | v1.26.1 | Stopped |     1 |        |
| dr2     | kvm2      | containerd | 192.168.122.61  | 8443 | v1.26.1 | Stopped |     1 |        |
| hub     | kvm2      | containerd | 192.168.122.250 | 8443 | v1.26.1 | Stopped |     1 |        |
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
```

**Comment by nirs** [comment]
The code assumes that we get successful response without server version. Looks like this is not true in all cases, but since we get the right json we can handle this better.
