### ISSUE TITLE
`ProtectedVRGList` controller crashes decoding zero byte VRG downloaded from s3

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#843]
Reported by @pdumbre
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x729a6e]

goroutine 732 [running]:
compress/gzip.(*Reader).Read(0x0, {0xc00313e400, 0x0, 0xc00084b258})
	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x2e
encoding/json.(*Decoder).refill(0xc002ec03c0)
	/usr/local/go/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc002ec03c0)
	/usr/local/go/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc002ec03c0, {0x1b542e0, 0xc002ed1400})
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
github.com/ramendr/ramen/controllers.(*s3ObjectStore).DownloadObject(0xc001b3c690, {0xc002f80a40, 0x3f}, {0x1b542e0, 0xc002ed1400})
	/workspace/controllers/s3utils.go:552 +0x625
github.com/ramendr/ramen/controllers.DownloadTypedObjects({0x1ed1778, 0xc001b3c690}, {0xc0039397e0, 0x1e}, {0x18375c0, 0xc0017bd830})
	/workspace/controllers/s3utils.go:467 +0x354
github.com/ramendr/ramen/controllers.DownloadVRGs(...)
	/workspace/controllers/s3utils.go:438
github.com/ramendr/ramen/controllers.(*ProtectedVolumeReplicationGroupListInstance).getVrgContentsFromS3(0xc00084bc00, {0xc001f15800, 0x4d, 0x80}, {0x1ed1778, 0xc001b3c690})
	/workspace/controllers/protectedvolumereplicationgrouplist_controller.go:151 +0x31a
github.com/ramendr/ramen/controllers.(*ProtectedVolumeReplicationGroupListReconciler).Reconcile(0xc000ab7680, {0x1ed14d8, 0xc001b0e000}, {{{0x0, 0x1abc5c0}, {0xc000d69960, 0x30}}})
	/workspace/controllers/protectedvolumereplicationgrouplist_controller.go:104 +0x61a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0007182c0, {0x1ed14d8, 0xc002d035c0}, {{{0x0, 0x1abc5c0}, {0xc000d69960, 0x413b94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007182c0, {0x1ed1430, 0xc000ab7600}, {0x19bcf40, 0xc000e817e0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007182c0, {0x1ed1430, 0xc000ab7600})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357
```
8 out of 10s of VRG objects were zero bytes, all with a write timestamp of the minute, 7:44 PM IST, that the primary cluster was shutdown and subsequently writes to it from that cluster were fenced.
```sh
$ mc ls myminio --recursive --insecure | grep -i VolumeReplicationGroup | grep 0B
[2023-04-20 19:44:12 IST]     0B STANDARD isf-minio-site1/ae1-fb-tarunk3/ae1-fb-tarunk3/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:13 IST]     0B STANDARD isf-minio-site1/ae1-fb-tarunk5/ae1-fb-tarunk5/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:12 IST]     0B STANDARD isf-minio-site1/ae1-md-tarunk3/ae1-md-tarunk3/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:13 IST]     0B STANDARD isf-minio-site1/ae1-md-tarunk4/ae1-md-tarunk4/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:13 IST]     0B STANDARD isf-minio-site1/ae1-md-tarunk5/ae1-md-tarunk5/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:13 IST]     0B STANDARD isf-minio-site1/ag1-fb-rek2/ag1-fb-rek2/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:12 IST]     0B STANDARD isf-minio-site1/one-ae1-wp3/one-ae1-wp3/v1alpha1.VolumeReplicationGroup/a
[2023-04-20 19:44:13 IST]     0B STANDARD isf-minio-site1/wp-fence-ae2-1/wp-fence-ae2-1/v1alpha1.VolumeReplicationGroup/a
```

**Comment by hatfieldbrian** [comment]
TODO: Add an upload log message

**Comment by hatfieldbrian** [comment]
Ramen assumes S3 store writes are atomic.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel
> Updates to a single key are atomic. For example, if you make a PUT request to an existing key from one thread and perform a GET request on the same key from a second thread concurrently, you will get either the old data or the new data, but never partial or corrupt data.

> This behavior applies to both writes to new objects as well as PUT requests that overwrite existing objects and DELETE requests.

MinIO is suspect

**Comment by hatfieldbrian** [comment]
Original report: https://github.com/RamenDR/ShioRamen/issues/87

**Comment by hatfieldbrian** [comment]
Labeled medium priority because this is reproducible with the cluster shutdown scenario.
